server:
  port: 9000

springdoc:
  api-docs:
    path: /api-docs


spring:
#  security:
#    user:
#      name: name
#      password: 123
#      roles: ADMIN

  datasource:
    url: jdbc:mysql://localhost:3306/blogdb
    username: root
    password: groot
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect